<?php
/**
 * Date: 9/28/19
 * Time: 11:04 AM
 */

namespace common\abstracts;


use yii\data\ActiveDataProvider;
use yii\web\Controller;

use yii;

abstract class BlogControllerAbstract extends Controller {


	public $model;
	public $modelName;
	protected $modelCategory;
	public $dataProvider;


	abstract public function getModelName();

	abstract public function postTypeName();

	abstract public function getLabelName();

	public function init() {
		$this->modelName = $this->getModelName();

		$this->model = new $this->modelName();

		//get postTypeCategory
		$postTypeCategory    = call_user_func( [ $this->model, 'postTypeCategory' ] );
		$this->modelCategory = new $postTypeCategory;

		$query = $this->model->find()->where( [ 'post_type' => $this->postTypeName() ] );

		$this->dataProvider = new ActiveDataProvider( [
			'query'      => $query,
			'pagination' => [
				'pageSize' => 10,
			],
		] );
		parent::init(); // TODO: Change the autogenerated stub
	}

	/**
	 * Lists all Blog models.
	 * @return mixed
	 */
	public function actionIndex() {

		$searchModel  = new BlogSearch();
		$dataProvider = $searchModel->search( Yii::$app->request->queryParams );

		return $this->render( 'index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
		] );
	}

	/**
	 * Displays a single Blog model.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView( $id ) {
		$model = $this->findModel( $id );


		return $this->render( 'view', [
			'model' => $model,
		] );
	}

	/**
	 * Creates a new Blog model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {

		$model    = new BlogModel();
		$upload   = new FileUpload();
		$file_uri = $upload->uploadFile( $model, 'image_url' );


		if ( $model->load( Yii::$app->request->post() ) ) {
			if ( ! empty( $file_uri ) ) {
				$model->image_url = $file_uri;
			}
			if ( $model->save() ) {
				Yii::$app->session->addFlash( 'success', "Update succeed" );
			}

			return $this->redirect( [ 'view', 'id' => $model->id ] );
		}


		return $this->render( 'create', [
			'model' => $model,
		] );
	}

	/**
	 * Updates an existing Blog model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate( $id ) {
		$model  = $this->findModel( $id );
		$upload = new FileUpload();

		$file_uri = $upload->uploadFile( $model, 'image_url' );

		if ( $model->load( Yii::$app->request->post() ) && $model->validate() ) {
			if ( ! empty( $file_uri ) ) {
				$model->image_url = $file_uri;
			}
			if ( $model->save() ) {
				Yii::$app->session->addFlash( 'success', "Update succeed" );
			}

			return $this->redirect( [ 'view', 'id' => $model->id ] );
		} else {
			var_dump( $model->getErrors() );
		}

		return $this->render( 'update', [
			'model' => $model,
		] );
	}

	/**
	 * Deletes an existing Blog model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete( $id ) {
		$model = $this->findModel( $id );
		$model->delete();

		FileUpload::deleteFile( $model, 'image_url' );

		return $this->redirect( [ 'index' ] );
	}

	/**
	 * Finds the Blog model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id
	 *
	 * @return BlogModel the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = BlogModel::findOne( $id ) ) !== null ) {
			return $model;
		}

		throw new NotFoundHttpException( 'The requested page does not exist.' );
	}









}