<?php
/**
 * Date: 9/27/19
 * Time: 11:37 AM
 */

namespace backend\models;


use common\abstracts\BlogModelAbtract;

class Product extends BlogModelAbtract {


	protected static $post_type = 'product';

	public function postTypeName() {
		// TODO: Implement postTypeName() method.
		return 'product';
	}

	public function postTypeCategory() {
		return ProductCat::class;
		// TODO: Implement postTypeCategory() method.
	}


	public function init() {
		self::$post_type = $this->postTypeName();
		parent::init(); // TODO: Change the autogenerated stub
	}


}