<?php
/**
 * Date: 9/24/19
 * Time: 4:12 PM
 */

namespace frontend\widgets;

use backend\models\Blog;
use yii\base\Exception;
use yii\helpers\ArrayHelper;

class BlogCardWidgets extends \yii\base\Widget {

	public $model;

	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		if ( ! empty( $this->model ) ) {

			$temp = [];
			foreach ( $this->model as $item ) {

				if ( is_object( $item ) ) {

					$temp[] = ArrayHelper::toArray( $item, [
						'backend\models\Blog' => [
							'id',
							'slug',
							'title',
							'description',
							'content',
							'image_url',
							'category',
						],
					] );
				}
			}
			$this->model = $temp;
		} else {
			throw new Exception( 'Missing model' );
		}
	}

	public function run() {
		return $this->render( 'blog', [ 'model' => $this->model ] );
	}


}